### ISSUE TITLE
AttributeError: 'file' object has no attribute 'peek'

### ISSUE THREAD

**Issue by benlindsay** [dib-lab/osf-cli#75]
Here's the traceback:

```
lindsb@rrlogin:~$ osf -p wy5pj -u lindsb@seas.upenn.edu upload 2016-12-15_usage_1.txt 2016-12-15_usage_1.txt
Traceback (most recent call last):
  File "/home/lindsb/usr/miniconda/bin/osf", line 11, in <module>
    load_entry_point('osfclient', 'console_scripts', 'osf')()
  File "/mnt/rrio1/home/lindsb/usr/osf-cli/osfclient/__main__.py", line 97, in main
    exit_code = args.func(args)
  File "/mnt/rrio1/home/lindsb/usr/osf-cli/osfclient/cli.py", line 214, in upload
    store.create_file(remote_path, fp, update=args.force)
  File "/mnt/rrio1/home/lindsb/usr/osf-cli/osfclient/models/storage.py", line 106, in create_file
    not_empty = fp.peek(1)
AttributeError: 'file' object has no attribute 'peek'
```

Any idea what's going on here?

Thanks in advance!

**Comment by betatim** [comment]
Not off the top of my head, I will take a look. Which version of python do you use?

**Comment by betatim** [comment]
If you are using python 2 then I think I know what the problem is and working on a fix :)

**Comment by benlindsay** [comment]
If the problem is python 2 then the solution is probably that I should stop being lazy and just update to python 3 :) This doesn't support 3.6 yet though right?

**Comment by betatim** [comment]
`osfclient` should work with python 3.6 😃 

Thanks for reporting the problem, clearly more of us need to use python 2 and we need a better strategy for testing to catch these things. I added a fix for this in #76.

**Comment by benlindsay** [comment]
Thanks! I look forward to having that working. Also as a side question, I know this would add complexity on your end, but any plans to have this hosted on pypi.org for a normal `pip install`?

**Comment by betatim** [comment]
We made a test/first release so you should now be able to `pip install osfclient`

**Comment by betatim** [comment]
Thanks for reporting this @benlindsay. Should be fixed now in master :tada:

**Comment by benlindsay** [comment]
Great, thanks!
